-- DROP TABLE myDW.MSC.Job;
-- TRUNCATE table  myDW.MSC.Job

CREATE TABLE myDW.MSC.Job (
	PCN int NOT NULL,
	JOBNUMBER nvarchar(32) NOT NULL,
	DESCR nvarchar(50) NOT NULL
);
-- TRUNCATE table  myDW.MSC.Jobs
select JOBNUMBER, descr 
from MSC.Job j
where j.DESCR like '%10103351%'
order by JOBNUMBER 


/*
 SELECT 
tlid,
VMID,
transtartdatetime,
TRANENDDATETIMe,
TRANSCODE,
USERNUMBER,
USERGROUP01, 
JOBNUMBER, 
ITEMNUMBER,
UNITCOST,
qty,
QTYNEW,
QTYONORDER,
ITEMGROUP, 
ITEMALIASNUMBER, 
SUPPLIERNUMBER,
SUPPLIERPARTNUMBER
FROM sps.dbo.TransactionLog
where transtartdatetime BETWEEN '2021-05-13 00:00:00' AND '2021-05-14 00:00:00'
and ITEMGROUP = 'INSERTS'

 */
/*
 * drop table myDW.AlbSPS.DWInfo
 */
/*
CREATE TABLE myDW.AlbSPS.DWInfo (
	ID int NOT NULL,
	LastImportSPSAlb datetime
);
*/
/*
-- myDW.AlbSPS.TransactionLog definition

-- Drop table

-- DROP TABLE myDW.AlbSPS.TransactionLog;

CREATE TABLE myDW.AlbSPS.TransactionLog (
	TLID decimal(27,15) NOT NULL,
	VMID int NULL,
	TRANSTARTDATETIME datetime NULL,
	TRANENDDATETIME datetime NULL,
	TRANSCODE nvarchar(3) NULL,
	ITEMNUMBER nvarchar(32) NULL,
	ITEMGROUP nvarchar(32) NULL,
	ITEMALIASNUMBER nvarchar(32) NULL,
	UNITCOST decimal(12,4) NULL,
	QTY int NULL,
	QTYNEW int NULL,
	QTYONORDER int NULL,
	SUPPLIERNUMBER nvarchar(32) NULL,
	SUPPLIERPARTNUMBER nvarchar(50) NULL,
	USERGROUP01 nvarchar(50) NULL,
	USERNUMBER nvarchar(32) NULL,
	JOBNUMBER nvarchar(32) NULL,
	CONSTRAINT PK_TRANSACTIONLOG PRIMARY KEY (TLID)
);
*/