DROP TABLE IF EXISTS DS13318
CREATE TABLE DS13318(
  DS13318_Key INT IDENTITY(1,1), 
  TransDate datetime DEFAULT NULL,
  PCN varchar(50) NULL,
  ProdServer bit NULL,
  Workcenter varchar(50) NULL,
  CNC varchar(25) NULL,
  Part_No varchar(50) NULL,
  Name varchar(50) NULL,
  Multiple bit NULL,
  Container_Note varchar(50) NULL,
  Cavity_Status_Key INT NULL,
  Container_Status varchar(50) NULL,
  Defect_Type varchar(50) NULL,
  Serial_No varchar(50) NULL,
  Setup_Container_Key INT NULL,
  Count int NULL,
  Part_Count int NULL,
  Part_Key INT NULL,
  Part_Operation_Key INT NULL,
  Standard_Container_Type varchar(50) NULL,
  Container_Type_Key INT NULL,
  Parent_Part varchar(50) NULL,
  Parent varchar(50) NULL,
  Cavity_No varchar(50) NULL,
  Master_Unit_Key INT NULL DEFAULT 0,
  Workcenter_Printer_Key INT NULL,
  Master_Unit_No varchar(50) NULL,
  Physical_Printer_Name varchar(50) NULL,
  Container_Count int NULL,
  Container_Quantity int NULL,
  Default_Printer varchar(50) NULL,
  Default_Printer_Key INT NULL,
  Class_Key INT NULL,
  Quantity INT NULL,
  Companion bit NULL,
  Container_Type varchar(50) NULL,
  Container_Type_Description varchar(100) NULL,
  Sort_Order int NULL
) 
