SELECT CustomerID, NameStyle, Title, FirstName, MiddleName, LastName, Suffix, CompanyName, SalesPerson, EmailAddress, Phone, PasswordHash, PasswordSalt, rowguid, ModifiedDate
FROM myDW.SalesLT.Customer;

SELECT CustomerID, AddressID, AddressType, rowguid, ModifiedDate
FROM myDW.SalesLT.CustomerAddress;

-- sps.dbo.TransactionLog definition

-- Drop table

-- DROP TABLE sps.dbo.TransactionLog;

CREATE TABLE myDW.dbo.TransactionLog (
	TLID decimal(27,15) NOT NULL,
	OPERATIONID int NULL,
	COMPTLID decimal(27,15) NULL,
	TRANSTARTDATETIME datetime NULL,
	TRANENDDATETIME datetime NULL,
	TRANSCODE nvarchar(3) COLLATE Latin1_General_CI_AS NULL,
	FUNCTIONCODE nvarchar(16) COLLATE Latin1_General_CI_AS NULL,
	ITEMNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	ITEMGROUP nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	ITEMALIASNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	BATCHNUMBER nvarchar(255) COLLATE Latin1_General_CI_AS NULL,
	LOCATIONTEXT nvarchar(255) COLLATE Latin1_General_CI_AS NULL,
	PONUMBER nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
	RELEASENUMBER nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
	PACKINGSLIPNUMBER nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
	EXPIRATIONDATE datetime NULL,
	VMID int NULL,
	PICNUMBER int NULL,
	DRAWERNUMBER int NULL,
	COMPARTMENTNUMBER int NULL,
	CONTENTTYPE nvarchar(1) COLLATE Latin1_General_CI_AS NULL,
	COSTCENTER nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	UNITCOST decimal(12,4) NULL,
	ISSUESIZE int NULL,
	PACKETSIZEANDSEC nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	OWNEDQTY int NULL,
	PARTIALQTY int NULL,
	QTY int NULL,
	QTYACTIVE int NULL,
	QTYGENERAL int NULL,
	QTYINASSY int NULL,
	QTYNEW int NULL,
	QTYONORDER int NULL,
	QTYREWORK int NULL,
	QTYUSED int NULL,
	TOOLLIFE int NULL,
	PIECECOUNT int NULL,
	TOOLFAILREASON nvarchar(255) COLLATE Latin1_General_CI_AS NULL,
	TOOLFAIL int NULL,
	RATIONEXCEEDEDINDICATOR nvarchar(255) COLLATE Latin1_General_CI_AS NULL,
	SUPPLIERNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	SUPPLIERPARTNUMBER nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERGROUP01 nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERGROUP02 nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERGROUP03 nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERGROUP04 nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERGROUP05 nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERGROUP06 nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERGROUP07 nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERGROUP08 nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERGROUP09 nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERGROUP10 nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	JOBGROUP nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	JOBNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	MACHINEGROUP nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	MACHINENUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	VIDEOCAPTUREFILE nvarchar(255) COLLATE Latin1_General_CI_AS NULL,
	PARENTID nvarchar(30) COLLATE Latin1_General_CI_AS NULL,
	LOGGEDINUSERNUMBER nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	SLIXBOXNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	REASON nvarchar(255) COLLATE Latin1_General_CI_AS NULL,
	AUX1 nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	AUX2 nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	AUX3 nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	CONFIRMED int NULL,
	ITEMVERIFICATIONCODE nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	UserOnOpenCS nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	UserOnCloseCS nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	USERCOSTCENTER nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	QTYCOUNTED int NULL,
	ITEMCOUNTED int NULL,
	ORDERLINENUMBER int NULL,
	LASTREPLACEDDATETIME datetime NULL,
	ORIGINALITEMNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	APISTATUS int DEFAULT 0 NULL,
	CONSTRAINT PK_TRANSACTIONLOG PRIMARY KEY (TLID)
);
 CREATE NONCLUSTERED INDEX IDX_COMPARTMENTNUMBER ON dbo.TransactionLog (  COMPARTMENTNUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_COMPTLID ON dbo.TransactionLog (  COMPTLID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_DRAWERNUMBER ON dbo.TransactionLog (  DRAWERNUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_ITEMALIASNUMBER ON dbo.TransactionLog (  ITEMALIASNUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_ITEMGROUP ON dbo.TransactionLog (  ITEMGROUP ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_ITEMNUMBER ON dbo.TransactionLog (  ITEMNUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_JOBNUMBER ON dbo.TransactionLog (  JOBNUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_MACHINENUMBER ON dbo.TransactionLog (  MACHINENUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_OPERATIONID ON dbo.TransactionLog (  OPERATIONID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_PICNUMBER ON dbo.TransactionLog (  PICNUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_SUPPLIERNUMBER ON dbo.TransactionLog (  SUPPLIERNUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_SUPPLIERPARTNUMBER ON dbo.TransactionLog (  SUPPLIERPARTNUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_TRANSCODE ON dbo.TransactionLog (  TRANSCODE ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_USERNUMBER ON dbo.TransactionLog (  USERNUMBER ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IDX_VMID ON dbo.TransactionLog (  VMID ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

