-- CREATE SCHEMA AlbSPS;
-- DROP TABLE myDW.AlbSPS.TransactionLog;

select * from myDW.AlbSPS.TransactionLog
select * from myDW.AlbSPS.test
select * from myDW.dbo.test

INSERT INTO myDW.AlbSPS.TransactionLog
(TLID, TRANSTARTDATETIME, TRANENDDATETIME, TRANSCODE, ITEMNUMBER, ITEMGROUP, ITEMALIASNUMBER, UNITCOST, QTY, QTYNEW, QTYONORDER, SUPPLIERNUMBER, SUPPLIERPARTNUMBER, USERGROUP01, USERNUMBER, JOBNUMBER)
VALUES(0, '', '', '', '', '', '', 0, 0, 0, 0, '', '', '', '', '');


/*
CREATE TABLE myDW.AlbSPS.TransactionLog (
	TLID decimal(27,15) NOT NULL,
	TRANSTARTDATETIME datetime NULL,
	TRANENDDATETIME datetime NULL,
	TRANSCODE nvarchar(3) COLLATE Latin1_General_CI_AS NULL,
	ITEMNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	ITEMGROUP nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	ITEMALIASNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	UNITCOST decimal(12,4) NULL,
	QTY int NULL,
	QTYNEW int NULL,
	QTYONORDER int NULL,
	SUPPLIERNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	SUPPLIERPARTNUMBER nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERGROUP01 nvarchar(50) COLLATE Latin1_General_CI_AS NULL,
	USERNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	JOBNUMBER nvarchar(32) COLLATE Latin1_General_CI_AS NULL,
	CONSTRAINT PK_TRANSACTIONLOG PRIMARY KEY (TLID)
);
*/