SELECT 
transtartdatetime,
TRANSCODE,
USERNUMBER,
USERGROUP01, 
JOBNUMBER, 
ITEMNUMBER,
UNITCOST,
qty,
QTYNEW,
QTYONORDER,
ITEMGROUP, 
ITEMALIASNUMBER, 
SUPPLIERNUMBER,
SUPPLIERPARTNUMBER
--TLID, OPERATIONID, COMPTLID, TRANSTARTDATETIME, TRANENDDATETIME, TRANSCODE, FUNCTIONCODE, ITEMNUMBER, ITEMGROUP, ITEMALIASNUMBER, BATCHNUMBER, LOCATIONTEXT, PONUMBER, RELEASENUMBER, PACKINGSLIPNUMBER, EXPIRATIONDATE, VMID, PICNUMBER, DRAWERNUMBER, COMPARTMENTNUMBER, CONTENTTYPE, COSTCENTER, UNITCOST, ISSUESIZE, PACKETSIZEANDSEC, OWNEDQTY, PARTIALQTY, QTY, QTYACTIVE, QTYGENERAL, QTYINASSY, QTYNEW, QTYONORDER, QTYREWORK, QTYUSED, TOOLLIFE, PIECECOUNT, TOOLFAILREASON, TOOLFAIL, RATIONEXCEEDEDINDICATOR, SUPPLIERNUMBER, SUPPLIERPARTNUMBER, USERGROUP01, USERGROUP02, USERGROUP03, USERGROUP04, USERGROUP05, USERGROUP06, USERGROUP07, USERGROUP08, USERGROUP09, USERGROUP10, USERNUMBER, JOBGROUP, JOBNUMBER, MACHINEGROUP, MACHINENUMBER, VIDEOCAPTUREFILE, PARENTID, LOGGEDINUSERNUMBER, SLIXBOXNUMBER, REASON, AUX1, AUX2, AUX3, CONFIRMED, ITEMVERIFICATIONCODE, UserOnOpenCS, UserOnCloseCS, USERCOSTCENTER, QTYCOUNTED, ITEMCOUNTED, ORDERLINENUMBER, LASTREPLACEDDATETIME, ORIGINALITEMNUMBER, APISTATUS
FROM sps.dbo.TransactionLog
where transtartdatetime > '2021-05-13 10:40:00'
and ITEMGROUP = 'INSERTS'
--itemaliannumber = 36207330
-- SUPPLIERPARTNUMBER = 2960855

